---
openshift_cluster_content:
- object: deployments
  content:
  - name: prometheus-stack
    namespace: monitoring
    template: "{{ inventory_dir }}/../files/templates/metrics.yml"
    params: "{{ inventory_dir }}/../files/params/prometheus-stack-params"
